UsersWithEmails/Models/Email.cs
namespace UsersWithEmails.Models
{
    public class Email
    {
        public long Id { get; private set; }
        public long PersonId { get; private set; }
        public virtual Person Person { get; private set; }
        public string Adress { get; private set; }

        public void Update(string adress)
        {
            Adress = adress;
        }
    }
}

UsersWithEmails/Models/ErrorViewModel.cs
namespace UsersWithEmails.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UsersWithEmails/Models/Person.cs
namespace UsersWithEmails.Models
{
    public class Person
    {
        public long Id { get; private set; }
        public string FirstName { get; private set; }
        public string LastName { get; private set; }
        public string? Remarks { get; private set; }

        public virtual List<Email> Emails { get; private set; }

        public void Update(string firstName, string lastName, string remarks)
        {
            FirstName = firstName;
            LastName = lastName;
            Remarks = remarks;
        }
    }
}

UsersWithEmails/Controllers/EmailController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using UsersWithEmails.Controllers.DTOs;
using UsersWithEmails.Data;
using UsersWithEmails.Models;

namespace UsersWithEmails.Controllers
{
    public class EmailController : Controller
    {
        private readonly IMapper mapper;
        private readonly IEmailRepository emailRepository;
        public EmailController(IMapper mapper, IEmailRepository emailRepository)
        {
            this.mapper = mapper;
            this.emailRepository = emailRepository;
        }

        [HttpGet("Email/GetEmailForUser/{personId}")]
        public async Task<ActionResult> GetEmailForUser(long personId)
        {
            var emails = await emailRepository.GetAllEmailsForPersonIdAsync(personId);
            ViewBag.PersonID = personId;
            return View(mapper.Map<List<EmailDTO>>(emails));
        }

        [HttpGet("Email/Create/{personId}")]
        public IActionResult Create(long personId)
        {
            ViewBag.PersonId = personId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmailFormDTO emailFromDTO)
        {
            var email = mapper.Map<Email>(emailFromDTO);
            await emailRepository.SaveAsync(email);
            return RedirectToAction("GetEmailForUser", new { id = emailFromDTO.PersonId });
        }

        [HttpGet("Email/Delete/{emailID}")]
        public async Task<IActionResult> Delete(long emailID)
        {
            var email = await emailRepository.GetEmailByIdAsync(emailID);
            await emailRepository.DeleteAsync(email);
            return RedirectToAction("GetEmailForUser", new { id = email.PersonId });
        }

        public async Task<IActionResult> Edit(long id)
        {
            var email = await emailRepository.GetEmailByIdAsync(id);

            return View(email);
        }

        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditPerson(long id, EmailFormDTO emailFormDTO)
        {
            var email = await emailRepository.GetEmailByIdAsync(id);
            email.Update(emailFormDTO.Adress);
            await emailRepository.UpdateAsync(email);

            return RedirectToAction("GetEmailForUser", new { id = email.PersonId });
        }
    }
}

UsersWithEmails/Controllers/PersonController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using UsersWithEmails.Controllers.DTOs;
using UsersWithEmails.Data;
using UsersWithEmails.Models;

namespace UsersWithEmails.Controllers
{
    public class PersonController : Controller
    {
        private readonly IMapper mapper;
        private readonly IPersonRepository personRepository;
        public PersonController(IMapper mapper, IPersonRepository personRepository)
        {
            this.mapper = mapper;
            this.personRepository = personRepository;
        }

        public async Task<IActionResult> Index()
        {
            var persons = await personRepository.GetAllAsync();
            return View(mapper.Map<List<PersonDTO>>(persons));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(PersonFromDTO personFromDTO)
        {
            var person = mapper.Map<Person>(personFromDTO);
            await personRepository.SaveAsync(person);
            return View();
        }

        [HttpGet("Person/Delete/{personID}")]
        public async Task<IActionResult> Delete(long personID)
        {
            var person = await personRepository.GetPersonByIdAsync(personID);
            await personRepository.DeleteAsync(person);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(long id)
        {
            var person = await personRepository.GetPersonByIdAsync(id);

            return View(person);
        }

        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditPerson(long id, PersonFromDTO personFromDTO)
        {
            var person = await personRepository.GetPersonByIdAsync(id);
            person.Update(personFromDTO.FirstName, personFromDTO.LastName, personFromDTO.Remarks);
            await personRepository.UpdateAsync(person);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> GeneratePersons()
        {
            var persons = PersonGenerator.GeneratePersonsWithEmail();
            await personRepository.SaveRangeAsync(persons);

            return RedirectToAction("Index");
        }
    }
}

UsersWithEmails/Views/Person/Create.cshtml
@model UsersWithEmails.Controllers.DTOs.PersonFromDTO

@{
    ViewData["Title"] = "Index";
}

<h1>Create</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Remarks" class="control-label"></label>
                <input asp-for="Remarks" class="form-control" />
                <span asp-validation-for="Remarks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UsersWithEmails/Views/Person/Edit.cshtml
@model UsersWithEmails.Models.Person

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Remarks" class="control-label"></label>
                <input asp-for="Remarks" class="form-control" />
                <span asp-validation-for="Remarks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UsersWithEmails/Views/Person/Index.cshtml
@model IEnumerable<UsersWithEmails.Controllers.DTOs.PersonDTO>

@{
    ViewData["Title"] = "View";
}

<h1>Person table</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <a asp-action="GeneratePersons">Generate records</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>            
            <th>
                @Html.DisplayNameFor(model => model.FirstEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Remarks)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.FirstEmail) <a asp-controller="Email" asp-action="GetEmailForUser" asp-route-id="@item.Id">Edit</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Remarks)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

UsersWithEmails/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UsersWithEmails</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UsersWithEmails.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Person" asp-action="Index">UsersWithEmails</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Person list</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - UsersWithEmails - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>